/**
 * Container for the Notificaciones screen.
 *
 * It owns which people are ticked, which rows are open and the download, and nothing else:
 * the grouping is `agruparFaltasPorPersona`, the cut into days is `separarPorDia`, and the
 * `.docx` is the notificaciones module. The document itself is still built in the browser —
 * no letter content is ever sent to the server.
 *
 * GENERATING A WORD IS WHAT MARKS ITS FALTAS AS NOTIFIED, so every download now makes ONE
 * request first: the (dni, fecha, tipo) keys the document covers, computed by
 * `clavesNotificadas` from exactly the persona(s) the document is built from, are recorded
 * through `useNotificadas().registrar`. Only when that succeeds is the file handed over
 * (`entregarRegistrado`); when it fails the operator reads why and nothing is downloaded, so
 * a letter never leaves the app without its record. All three paths — per person, per day
 * and the mass file — go through `entregar` below.
 */

import { useCallback, useMemo, useRef, useState } from 'react';

import { generarWord, generarWordDia, generarWordMasivo, MIME_DOCX, type DocumentoGenerado, type NotificacionPersona } from '../../../notificaciones/index.js';
import { useConfiguracion } from '../../configuracion/ConfiguracionProvider.js';
import { agruparFaltasPorPersona } from '../../faltas/agrupacion.js';
import { clavesNotificadas, separarPorDia, type ClaveNotificada } from '../../faltas/porDia.js';
import { useHistorial } from '../../historial/HistorialProvider.js';
import { useNotificadas } from '../../notificaciones/NotificadasProvider.js';
import { usePeriodo } from '../../periodo/PeriodoProvider.js';
import { NotificacionesScreen } from './NotificacionesScreen.js';
import { entregarRegistrado, MENSAJE_SIN_REGISTRO } from './notificaciones.js';

/**
 * Hands the browser a file it already has in memory.
 *
 * The same shape as the one in `AusenciasContainer`, kept local on purpose: it is four
 * lines of DOM glue that each container owns, and a shared helper would be a module whose
 * only job is to make two screens import each other's plumbing.
 */
function guardarComo(blob: Blob, nombre: string): void {
  const url = URL.createObjectURL(blob);
  try {
    const enlace = document.createElement('a');
    enlace.href = url;
    enlace.download = nombre;
    enlace.rel = 'noopener';
    document.body.append(enlace);
    enlace.click();
    enlace.remove();
  } finally {
    // A tick, so the click has started the download before the handle goes away.
    setTimeout(() => URL.revokeObjectURL(url), 0);
  }
}

/**
 * The generated bytes as a `.docx` Blob.
 *
 * The cast is what TypeScript 5.7 asks for and nothing more: `Uint8Array` became generic
 * over its buffer, `fflate` hands back the unparameterised `Uint8Array<ArrayBufferLike>`,
 * and `BlobPart` only accepts a view over a plain `ArrayBuffer`. `zipSync` allocates a plain
 * one — no `SharedArrayBuffer` exists anywhere in this path — so the only alternative would
 * be copying a whole document to satisfy the checker.
 */
function comoDocx(bytes: Uint8Array): Blob {
  return new Blob([bytes as Uint8Array<ArrayBuffer>], { type: MIME_DOCX });
}

/**
 * The DNIs of `marcados` that are still on screen. Selection and open rows both go through
 * it: changing the period replaces the whole list, and a DNI that is no longer on screen must
 * neither count towards "Generar seleccionadas" nor show as open. Derived rather than pruned
 * in an effect, because an effect would render once with the stale state before correcting it.
 */
function soloVisibles(
  marcados: ReadonlySet<string>,
  personas: readonly NotificacionPersona[],
): ReadonlySet<string> {
  return new Set(personas.filter((p) => marcados.has(p.dni)).map((p) => p.dni));
}

export function NotificacionesContainer() {
  const { registros, cargando } = useHistorial();
  const { paraElMotor } = useConfiguracion();
  const { rango } = usePeriodo();

  const personas = useMemo(
    () => agruparFaltasPorPersona(registros, paraElMotor, rango),
    [registros, paraElMotor, rango],
  );

  const [seleccionadas, setSeleccionadas] = useState<ReadonlySet<string>>(() => new Set());

  const vigentes = useMemo(() => soloVisibles(seleccionadas, personas), [personas, seleccionadas]);

  // Raw, like Horas: the screen only ever sees `abiertas`, and every toggle starts from that
  // derived set, so a period change needs no effect to close anything.
  const [abiertasCrudas, setAbiertas] = useState<ReadonlySet<string>>(() => new Set());
  const abiertas = useMemo(() => soloVisibles(abiertasCrudas, personas), [abiertasCrudas, personas]);

  // Only the open rows are cut into days: that is all the screen lists, and the split of a
  // closed row would be thrown away on every render.
  const dias = useMemo(
    () => new Map(personas.filter((p) => abiertas.has(p.dni)).map((p) => [p.dni, separarPorDia(p)])),
    [personas, abiertas],
  );

  const alternarDetalle = useCallback(
    (dni: string) => {
      const siguientes = new Set(abiertas);
      if (siguientes.has(dni)) siguientes.delete(dni);
      else siguientes.add(dni);
      setAbiertas(siguientes);
    },
    [abiertas],
  );

  const alternar = useCallback((dni: string) => {
    setSeleccionadas((previas) => {
      const siguientes = new Set(previas);
      if (siguientes.has(dni)) siguientes.delete(dni);
      else siguientes.add(dni);
      return siguientes;
    });
  }, []);

  const alternarTodas = useCallback(
    (marcado: boolean) => setSeleccionadas(marcado ? new Set(personas.map((p) => p.dni)) : new Set()),
    [personas],
  );

  const { notificadas, registrar, error: errorLectura } = useNotificadas();
  const [errorRegistro, setErrorRegistro] = useState<string | null>(null);
  // One document at a time: a second click while the record is in flight would post the
  // same keys again and download twice.
  // The ref closes the gap before the disabled buttons re-render; the state disables them.
  const [registrando, setRegistrando] = useState(false);
  const enVuelo = useRef(false);

  /**
   * The ONE way a document leaves this screen: record the keys it covers, then download.
   * `claves` must come from the same `NotificacionPersona` values the document was built
   * from, which every caller below guarantees by computing both from one variable.
   */
  const entregar = useCallback(
    async (claves: readonly ClaveNotificada[], doc: DocumentoGenerado) => {
      if (enVuelo.current) return;
      enVuelo.current = true;
      setErrorRegistro(null);
      setRegistrando(true);
      try {
        const resultado = await entregarRegistrado(claves, registrar, () =>
          guardarComo(comoDocx(doc.bytes), doc.nombreArchivo),
        );
        if (resultado === 'no_registrado') setErrorRegistro(MENSAJE_SIN_REGISTRO);
      } finally {
        enVuelo.current = false;
        setRegistrando(false);
      }
    },
    [registrar],
  );

  const generarPersona = useCallback(
    (dni: string) => {
      const persona = personas.find((p) => p.dni === dni);
      if (!persona) return;
      // Null means the person has no falta to notify, so there is no document and nothing
      // to hand over.
      const doc = generarWord(persona);
      if (!doc) return;
      void entregar(clavesNotificadas(persona), doc);
    },
    [personas, entregar],
  );

  /**
   * The ONE way a single day's letter is produced. It resolves the day from the same split the
   * screen listed, so what is downloaded — and recorded — is exactly the row the operator
   * clicked: `clavesNotificadas(delDia.persona)` covers that day and nothing else.
   */
  const generarDia = useCallback(
    (dni: string, fecha: string) => {
      const persona = personas.find((p) => p.dni === dni);
      if (!persona) return;
      const delDia = separarPorDia(persona).find((d) => d.fecha === fecha);
      if (!delDia) return;
      const doc = generarWordDia(delDia.persona, delDia.fecha);
      if (!doc) return;
      void entregar(clavesNotificadas(delDia.persona), doc);
    },
    [personas, entregar],
  );

  const generarSeleccionadas = useCallback(() => {
    const elegidas = personas.filter((p) => vigentes.has(p.dni));
    const doc = generarWordMasivo(elegidas);
    if (!doc) return;
    void entregar(elegidas.flatMap((p) => clavesNotificadas(p)), doc);
  }, [personas, vigentes, entregar]);

  return (
    <NotificacionesScreen
      personas={personas}
      seleccionadas={vigentes}
      abiertas={abiertas}
      dias={dias}
      notificadas={notificadas}
      cargando={cargando}
      registrando={registrando}
      error={errorRegistro ?? (errorLectura ? `No se pudo leer qué faltas ya están notificadas: ${errorLectura}` : null)}
      onAlternar={alternar}
      onAlternarTodas={alternarTodas}
      onAlternarDetalle={alternarDetalle}
      onGenerarPersona={generarPersona}
      onGenerarDia={generarDia}
      onGenerarSeleccionadas={generarSeleccionadas}
    />
  );
}
