/**
 * Container for the Notificaciones screen.
 *
 * It owns which people are ticked and the download, and nothing else: the grouping is
 * `agruparFaltasPorPersona` and the `.docx` is the notificaciones module. Both are pure, so
 * the whole document is built in the browser — nothing about a disciplinary letter is sent
 * to the server, and there is no request to fail halfway.
 */

import { useCallback, useMemo, useState } from 'react';

import { generarWord, generarWordMasivo, MIME_DOCX } from '../../../notificaciones/index.js';
import { useConfiguracion } from '../../configuracion/ConfiguracionProvider.js';
import { agruparFaltasPorPersona } from '../../faltas/agrupacion.js';
import { useHistorial } from '../../historial/HistorialProvider.js';
import { usePeriodo } from '../../periodo/PeriodoProvider.js';
import { NotificacionesScreen } from './NotificacionesScreen.js';

/**
 * Hands the browser a file it already has in memory.
 *
 * The same shape as the one in `AusenciasContainer`, kept local on purpose: it is four
 * lines of DOM glue that each container owns, and a shared helper would be a module whose
 * only job is to make two screens import each other's plumbing.
 */
function guardarComo(blob: Blob, nombre: string): void {
  const url = URL.createObjectURL(blob);
  try {
    const enlace = document.createElement('a');
    enlace.href = url;
    enlace.download = nombre;
    enlace.rel = 'noopener';
    document.body.append(enlace);
    enlace.click();
    enlace.remove();
  } finally {
    // A tick, so the click has started the download before the handle goes away.
    setTimeout(() => URL.revokeObjectURL(url), 0);
  }
}

/**
 * The generated bytes as a `.docx` Blob.
 *
 * The cast is what TypeScript 5.7 asks for and nothing more: `Uint8Array` became generic
 * over its buffer, `fflate` hands back the unparameterised `Uint8Array<ArrayBufferLike>`,
 * and `BlobPart` only accepts a view over a plain `ArrayBuffer`. `zipSync` allocates a plain
 * one — no `SharedArrayBuffer` exists anywhere in this path — so the only alternative would
 * be copying a whole document to satisfy the checker.
 */
function comoDocx(bytes: Uint8Array): Blob {
  return new Blob([bytes as Uint8Array<ArrayBuffer>], { type: MIME_DOCX });
}

export function NotificacionesContainer() {
  const { registros, cargando } = useHistorial();
  const { paraElMotor } = useConfiguracion();
  const { rango } = usePeriodo();

  const personas = useMemo(
    () => agruparFaltasPorPersona(registros, paraElMotor, rango),
    [registros, paraElMotor, rango],
  );

  const [seleccionadas, setSeleccionadas] = useState<ReadonlySet<string>>(() => new Set());

  // Changing the period replaces the whole list, and a DNI that is no longer on screen must
  // not keep counting towards "Generar seleccionadas". Derived rather than pruned in an
  // effect: an effect would render once with the stale count before correcting itself.
  const vigentes = useMemo(
    () => new Set(personas.filter((p) => seleccionadas.has(p.dni)).map((p) => p.dni)),
    [personas, seleccionadas],
  );

  const alternar = useCallback((dni: string) => {
    setSeleccionadas((previas) => {
      const siguientes = new Set(previas);
      if (siguientes.has(dni)) siguientes.delete(dni);
      else siguientes.add(dni);
      return siguientes;
    });
  }, []);

  const alternarTodas = useCallback(
    (marcado: boolean) => setSeleccionadas(marcado ? new Set(personas.map((p) => p.dni)) : new Set()),
    [personas],
  );

  const generarPersona = useCallback(
    (dni: string) => {
      const persona = personas.find((p) => p.dni === dni);
      if (!persona) return;
      // Null means the person has no falta to notify, so there is no document and nothing
      // to hand over.
      const doc = generarWord(persona);
      if (!doc) return;
      guardarComo(comoDocx(doc.bytes), doc.nombreArchivo);
    },
    [personas],
  );

  const generarSeleccionadas = useCallback(() => {
    const doc = generarWordMasivo(personas.filter((p) => vigentes.has(p.dni)));
    if (!doc) return;
    guardarComo(comoDocx(doc.bytes), doc.nombreArchivo);
  }, [personas, vigentes]);

  return (
    <NotificacionesScreen
      personas={personas}
      seleccionadas={vigentes}
      cargando={cargando}
      onAlternar={alternar}
      onAlternarTodas={alternarTodas}
      onGenerarPersona={generarPersona}
      onGenerarSeleccionadas={generarSeleccionadas}
    />
  );
}
